name: godot-ci-node
description: Docker image based off of godot-ci with nodejs support added, primarily for godot 4.5
author: aBarichello
branding:
  color: gray-dark
  icon: git-merge
runs: 
  using: 'docker'
  image: 'docker://gremling/godot-ci-node'
